web:
  image: nginx:1.13.12
  ports:
    - "8080:80"
  links:
    - php
  volumes: 
    - ./html:/html
    - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    - ./logs/nginx-error.log:/var/log/nginx/error.log
    - ./logs/nginx-access.log:/var/log/nginx/access.log

php:
  image: php:7.2-fpm
  ports:
    - "9000:9000"
  volumes: 
    - ./html:/html

db:
  image: mariadb:10.3.7
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: P1Vxroi
  volumes:
    - ./mysql:/var/lib/mysql

adminer:
  image: adminer:4.6.2-standalone
  restart: always
  links:
    - db
  ports:
    - 8081:8080
